version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      # These variables are used by the postgres image to set up the database.
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: contacts_db
    ports:
      # Map the container's port to a port on the host machine.
      - "5432:5432"
    volumes:
      # This ensures data persists even if the container is removed.
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
